#!/bin/bash

export ISTIO_VERSION="1.4.6"

export PROJECT_ID="bl-darkmatter"

export CLUSTER_NAME="cloudstate"

export CLUSTER_REGION="us-central1"

export CLUSTER_ZONE="us-central1-c"

export CLUSTER_START_NODE_SIZE=2

export CLUSTER_MAX_NODE_SIZE=6

export CLUSTER_NODE_MACHINE_TYPE="n1-standard-4"

export CLUSTER_MASTER_VERSION="latest"